spin_manifest_version = 2

[application]
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = "Generate Tailscale authkey"
name = "gitops-tailscale-authkey"
version = "0.1.0"

[[trigger.ghaction]]
component = "generate-authkey"

[component.generate-authkey]
source = "main.wasm"
allowed_outbound_hosts = [
  "https://api.tailscale.com",
]

[component.generate-authkey.build]
command = "tinygo build -target=wasip2 --wit-package $(go list -mod=readonly -m -f '{{.Dir}}' github.com/spinframework/spin-go-sdk/v2)/wit --wit-world http-trigger -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
